[package]
name = "ascii_dice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
crossterm = "0.22"
anyhow = "1.0.82"
num-traits = "0.2"
